// Filename : sobel.h
//
// This file was initially generated by SpaceStudio but is meant to be modified
// by the user.
#ifndef SOBEL_H
#define SOBEL_H

#include "spacecomp.h"
#include "abstract_module.h"
#include "application_definitions.h"

// Do NOT move macros, functions and includes beginning with "spacecomp".

class sobel: public abstract_module {
	SPACECOMP_START(sobel, INDEX, sobel);

public:
	sobel(SPACECOMP_CTOR_PARAMS(sobel, INDEX));

	void thread(SPACECOMP_THREAD_PARAMS(sobel, INDEX, thread));

	// You may add member functions and fields as desired here.

	SPACECOMP_END(sobel, INDEX, sobel);

private:
	void sobel_operator(uint8_t* input, uint8_t* output, uint32_t img_width, uint32_t img_height);
	uint8_t perform_kernel(const uint32_t index, const uint32_t img_width, uint8_t* input);
	uint8_t getVal(int index, int xDiff, int yDiff, int img_width, uint8_t* input);
};

#endif
